# Generated by Django 4.2.17 on 2025-01-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_view',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user_view',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_view',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
