# Generated by Django 4.2.17 on 2025-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_head_of_institution',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Utilisateur', 'Utilisateur'), ("Chef d'etablissement", "Chef d'etablissement"), ('Administrateur', 'Administrateur')], default='Utilisateur', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='237000000000', max_length=15, unique=True),
        ),
    ]
